### ISSUE TITLE
Prompt for importing package after successful installation, but still prompt for not being found

### ISSUE THREAD

**Issue by XianYue0125** [lovemefan/CT-Transformer-punctuation#1]
Hello, I used version 0.0.1 before and successfully installed the package according to the tutorial at that time. Now when I install it, it will change to 0.0.2. After installation, importing the package will prompt that the definition cannot be found. I have tried installing it in different locations many times but it still doesn't work.

What can be guaranteed is that they are all in the same virtual environment and will not install the wrong environment.

（The content was translated using translation software and may not read naturally）

**Comment by lovemefan** [comment]
> Hello, I used version 0.0.1 before and successfully installed the package according to the tutorial at that time. Now when I install it, it will change to 0.0.2. After installation, importing the package will prompt that the definition cannot be found. I have tried installing it in different locations many times but it still doesn't work.
> 
> What can be guaranteed is that they are all in the same virtual environment and will not install the wrong environment.
> 
> （The content was translated using translation software and may not read naturally）

Chinese is ok, can you provide more details about  your code and exception ?

你好，用中文也可以的，我没有复现你说的问题，可以提供一下你的代码和错误信息吗?

**Comment by XianYue0125** [comment]
我先提两个建议：

1、考虑在安装的教程里面加入curl -o cttpunctuator/src/onnx/punc.onnx "https://huggingface.co/lovemefan/ctt_punctuator/resolve/main/cttpunctuator/src/onnx/punc.onnx"的代码，我对这个也不是很懂，一直没运行成功，我以前是复制网址到网站去下载模型的，后来问gpt，才知道curl可以下载

2、目前按照教程安装的过程会报错
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.14.1 (from cttpunctuator) (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.3)
ERROR: No matching distribution found for onnxruntime==1.14.1
我使用的是3.11.8版本，我想可能和这个有关，或者可以的话不是指定版本而是给定一个版本号的区间

**Comment by XianYue0125** [comment]
![image](https://github.com/lovemefan/CT-Transformer-punctuation/assets/143397470/0cab9644-4905-4193-b8a9-dc625f05aa35)

(venv) E:\ZWT\python_project\ctt>e:/ZWT/python_project/ctt/venv/Scripts/python.exe e:/ZWT/python_project/ctt/test.py
Traceback (most recent call last):
  File "e:\ZWT\python_project\ctt\test.py", line 1, in <module>
    from cttPunctuator import CttPunctuator
ModuleNotFoundError: No module named 'cttPunctuator'

这是目前我遇到的情况

**Comment by XianYue0125** [comment]
from cttpunctuator import CttPunctuator

改成小写也不行

**Comment by lovemefan** [comment]
> from cttpunctuator import CttPunctuator
> 
> 改成小写也不行

我初步推定是安装路径和当前PYTHONPATH冲突导致，cttpunctuator可以当作是一个第三方包，和pip install 安装的包一样可以直接使用，我的建议是尝试新建一个工程然后运行test.py 。确保test.py 和CT-Transformer-punctuation项目不在同一个文件夹下。

**Comment by XianYue0125** [comment]
![image](https://github.com/lovemefan/CT-Transformer-punctuation/assets/143397470/f496719c-8c64-4544-b1f4-0eec047ddaea)

是这样吗

**Comment by lovemefan** [comment]
> 我先提两个建议：
> 
> 1、考虑在安装的教程里面加入curl -o cttpunctuator/src/onnx/punc.onnx "[https://huggingface.co/lovemefan/ctt_punctuator/resolve/main/cttpunctuator/src/onnx/punc.onnx"的代码，我对这个也不是很懂，一直没运行成功，我以前是复制网址到网站去下载模型的，后来问gpt，才知道curl可以下载](https://huggingface.co/lovemefan/ctt_punctuator/resolve/main/cttpunctuator/src/onnx/punc.onnx%22%E7%9A%84%E4%BB%A3%E7%A0%81%EF%BC%8C%E6%88%91%E5%AF%B9%E8%BF%99%E4%B8%AA%E4%B9%9F%E4%B8%8D%E6%98%AF%E5%BE%88%E6%87%82%EF%BC%8C%E4%B8%80%E7%9B%B4%E6%B2%A1%E8%BF%90%E8%A1%8C%E6%88%90%E5%8A%9F%EF%BC%8C%E6%88%91%E4%BB%A5%E5%89%8D%E6%98%AF%E5%A4%8D%E5%88%B6%E7%BD%91%E5%9D%80%E5%88%B0%E7%BD%91%E7%AB%99%E5%8E%BB%E4%B8%8B%E8%BD%BD%E6%A8%A1%E5%9E%8B%E7%9A%84%EF%BC%8C%E5%90%8E%E6%9D%A5%E9%97%AEgpt%EF%BC%8C%E6%89%8D%E7%9F%A5%E9%81%93curl%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD)
> 
> 2、目前按照教程安装的过程会报错 ERROR: Could not find a version that satisfies the requirement onnxruntime==1.14.1 (from cttpunctuator) (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.3) ERROR: No matching distribution found for onnxruntime==1.14.1 我使用的是3.11.8版本，我想可能和这个有关，或者可以的话不是指定版本而是给定一个版本号的区间

感谢提出的建议，由于我个人测试情况有限，你的建议有利于让开源工具更加的完善和方便。
1.  提供了wget 工具，但确实没有考虑到windows用户可能没有安装，后续将在readme补充说明
2.  之前没有测试python3.11 , 已经补充相关测试， [详见如下](https://github.com/lovemefan/CT-Transformer-punctuation/actions/runs/8842505258/job/24281274355)

**Comment by lovemefan** [comment]
> ![image](https://private-user-images.githubusercontent.com/143397470/325837669-f496719c-8c64-4544-b1f4-0eec047ddaea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDE4MjYsIm5iZiI6MTcxNDEwMTUyNiwicGF0aCI6Ii8xNDMzOTc0NzAvMzI1ODM3NjY5LWY0OTY3MTljLThjNjQtNDU0NC1iMWY0LTBlZWMwNDdkZGFlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMzE4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTE5YTEzYjIwODg0ZDMyOTA5MmI1ZDIxMzhiMmZiNmZlNGYwNGQ4NTEwZmE2YTU4NDdkNTcxZGQxMjc5NmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nv8pM19N59lNOoBUqZCwJSDPc_fOzV2LLEXGeHO15OI)
> 
> 是这样吗

这样的话，你修改了原来包的位置，需要重新运行pip install -e .     你也可以直接使用 pip install .  
 带不带-e 参数， 区别是如果有 -e , python会从e:/ZWT/python_project/ctt/CT-Transformer-punctuation这个路径找你import的代码， 你可以修改代码，修改及生效。如果不使用 -e 参数，pip会将改项目copy 一份到e:/ZWT/python_project/ctt/venv里面，变成一个第三方包，修改原来代码无效。

**Comment by XianYue0125** [comment]
![image](https://github.com/lovemefan/CT-Transformer-punctuation/assets/143397470/db4b7114-e20a-4559-a10e-de87cba5d249)

我尝试了pip install -e . 和pip install . 

好像没有效果

**Comment by lovemefan** [comment]
> ![image](https://private-user-images.githubusercontent.com/143397470/325840465-db4b7114-e20a-4559-a10e-de87cba5d249.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDI4OTYsIm5iZiI6MTcxNDEwMjU5NiwicGF0aCI6Ii8xNDMzOTc0NzAvMzI1ODQwNDY1LWRiNGI3MTE0LWUyMGEtNDU1OS1hMTBlLWRlODdjYmE1ZDI0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMzM2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTYwZDVhMjcwMDYzNGFjZTdlM2IwZGYyNDM2NWZiMjJkOGFkNDYyYmRhODExZTU5OTkwNjgwMjY3M2NlNWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B0KWqpfovjRendnfER9WC0S2t8SfDRZVJfSZQBgUP-c)
> 
> 我尝试了pip install -e . 和pip install .
> 
> 好像没有效果

请在控制台运行以下命令，查看当前虚环境位置  python -c "import sys;print(sys.executable)"， 以及运行python test.py的效果

**Comment by XianYue0125** [comment]
![image](https://github.com/lovemefan/CT-Transformer-punctuation/assets/143397470/45b9c19b-08f3-47d6-84e6-afee9d4500c8)

**Comment by lovemefan** [comment]
> ![image](https://private-user-images.githubusercontent.com/143397470/325849691-45b9c19b-08f3-47d6-84e6-afee9d4500c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTAzNDUsIm5iZiI6MTcxNDExMDA0NSwicGF0aCI6Ii8xNDMzOTc0NzAvMzI1ODQ5NjkxLTQ1YjljMTliLTA4ZjMtNDdkNi04NGU2LWFmZWU5ZDQ1MDBjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwNTQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Njk2NzhjODc0NmFlOWQ3MGYxN2I3ZTY5MzQxYTliNTUxYThhMjZjZDY3Mzg5M2EyY2Q3OTgzNmU0YTdkMjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XZ7KgWYQ425EImU356OpmX81TpmDY49KNb9xkATjSl8)

控制台虚环境与vscode运行的虚环境不一致，请先在控制台激活vscode使用的虚环境，然后在重新安装

**Comment by XianYue0125** [comment]
我尝试了一下，可以了，是我操作的问题

感谢！
